import type { Metadata } from "next";
import { ThemeProvider } from "next-themes";
import "./globals.css";
import { Comic_Neue } from "next/font/google";
import SessionWrapper from "@/components/SessionWrapper";
import Header from "@/components/Header";

const comic = Comic_Neue({
  weight: ["300", "400", "700"],
  subsets: ["latin"],
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <SessionWrapper>
      <html lang="en">
        <body className={comic.className}>
          <ThemeProvider attribute="class">
            <div className="flex flex-col min-h-screen">
              <Header />
              <div className="bg-no-repeat bg-cover bg-[top_center] bg-[url('/Homepage.svg')]">
                {children}
              </div>
            </div>
          </ThemeProvider>
        </body>
      </html>
    </SessionWrapper>
  );
}
